#!/usr/bin/env python3
# Generates Localizable.strings for each supported language from an inline
# translation table. Keys are either the literal English UI string (SwiftUI's
# implicit LocalizedStringKey lookup) or an explicit "Namespace.key" used with
# String(localized:defaultValue:).

import os

BASE = "Sources/TokenOutApp/Resources"

# id -> English source text (also the literal key for plain Text() strings)
EN = {
    "30 days": "30 days",
    "30d": "30d",
    "60 days": "60 days",
    "60d": "60d",
    "7 days": "7 days",
    "7d": "7d",
    "90 days": "90 days",
    "90d": "90d",
    "A few Google Fonts, alongside the system font.": "A few Google Fonts, alongside the system font.",
    "API-equivalent cost": "API-equivalent cost",
    "About": "About",
    "Alerts": "Alerts",
    "All providers": "All providers",
    "All usage data stays on this Mac. No analytics, telemetry, or TokenOut account.": "All usage data stays on this Mac. No analytics, telemetry, or TokenOut account.",
    "Appearance": "Appearance",
    "Automatic refresh": "Automatic refresh",
    "Automatically check for updates": "Automatically check for updates",
    "TokenOut looks for Claude Code and Codex.": "TokenOut looks for Claude Code and Codex.",
    "TokenOut reads each tool's own local data and uses only its existing sign-in.": "TokenOut reads each tool's own local data and uses only its existing sign-in.",
    "TokenOut speeds up automatically above 50% usage and backs off after failures.": "TokenOut speeds up automatically above 50% usage and backs off after failures.",
    "TokenOut stays in the menu bar and has no Dock icon.": "TokenOut stays in the menu bar and has no Dock icon.",
    "Check for Updates…": "Check for Updates…",
    "Connected": "Connected",
    "Daily usage charts": "Daily usage charts",
    "Daily usage": "Daily usage",
    "Daily": "Daily",
    "Default popover": "Default popover",
    "Detected": "Detected",
    "Display": "Display",
    "Download and install updates automatically": "Download and install updates automatically",
    "Each alert is sent once per rate-limit reset cycle.": "Each alert is sent once per rate-limit reset cycle.",
    "Every 6 hours": "Every 6 hours",
    "Every hour": "Every hour",
    "First launch": "First launch",
    "General": "General",
    "Language": "Language",
    "Launch TokenOut at login": "Launch TokenOut at login",
    "Limit notifications": "Limit notifications",
    "Manual update": "Manual update",
    "Menu bar": "Menu bar",
    "Model and project breakdowns": "Model and project breakdowns",
    "No AI coding tools detected": "No AI coding tools detected",
    "No usage recorded in this range.": "No usage recorded in this range.",
    "Not detected": "Not detected",
    "Notifications": "Notifications",
    "Notify when a limit refills": "Notify when a limit refills",
    "Now": "Now",
    "Popover content": "Popover content",
    "Provider detail tiles": "Provider detail tiles",
    "Providers": "Providers",
    "Quota unavailable": "Quota unavailable",
    "Refresh": "Refresh",
    "Refreshing…": "Refreshing…",
    "Restart TokenOut for a language change to fully apply.": "Restart TokenOut for a language change to fully apply.",
    "Show onboarding again": "Show onboarding again",
    "Signed out": "Signed out",
    "Some updates failed": "Some updates failed",
    "Sparkle updates": "Sparkle updates",
    "Stale": "Stale",
    "Start tracking": "Start tracking",
    "Startup": "Startup",
    "TOKENS": "TOKENS",
    "Theme": "Theme",
    "Thresholds": "Thresholds",
    "Tokens": "Tokens",
    "Tracked tools": "Tracked tools",
    "Updated": "Updated",
    "Updates are signed twice: with Developer ID and TokenOut's Sparkle EdDSA key.": "Updates are signed twice: with Developer ID and TokenOut's Sparkle EdDSA key.",
    "Updates": "Updates",
    "Updating…": "Updating…",
    "Useful when reviewing local-data access and the Claude Keychain prompt.": "Useful when reviewing local-data access and the Claude Keychain prompt.",
    "Weekly": "Weekly",
    "What's left — drains to 0%": "What's left — drains to 0%",
    "What's used — fills to 100%": "What's used — fills to 100%",
    "Your AI usage, live in the menu bar.": "Your AI usage, live in the menu bar.",
    "estimated locally": "estimated locally",
    "Fetching fresh data…": "Fetching fresh data…",
    "Plot charts by dollars or tokens": "Plot charts by dollars or tokens",
    "Quit TokenOut": "Quit TokenOut",
    "Refresh all providers now (15 s cooldown)": "Refresh all providers now (15 s cooldown)",
    "Settings": "Settings",
    "Theme.system": "System",
    "Theme.light": "Light",
    "Theme.dark": "Dark",
    "FontSize.small": "Small",
    "FontSize.medium": "Medium",
    "FontSize.large": "Large",
    "FontSize.extraLarge": "Extra Large",
    "Font.system": "System",
    "Language.system": "System",
    "Overview": "Overview",
    "Relaunch Now": "Relaunch Now",
    "Primary metric": "Primary metric",
    "Style": "Style",
    "Limits show": "Limits show",
    "Default chart range": "Default chart range",
    "Chart metric": "Chart metric",
    "Open on": "Open on",
    "Cadence": "Cadence",
    "Check frequency": "Check frequency",
    "App language": "App language",
    "Size": "Size",
    "Font": "Font",
    "Warning": "Warning",
    "Critical": "Critical",
    "Website": "Website",
    "Privacy": "Privacy",
    "Percent only": "Percent only",
    "Tightest limit": "Tightest limit",
    "Fast (30 s)": "Fast (30 s)",
    "Normal (60 s)": "Normal (60 s)",
    "Relaxed (5 min)": "Relaxed (5 min)",
    "refills in %1$@ · at %2$@": "refills in %1$@ · at %2$@",
    "refilled · refreshing…": "refilled · refreshing…",
    "%@ over pace": "%@ over pace",
    "%@ in reserve": "%@ in reserve",
    "on pace": "on pace",
    "Used %1$@ of the quota with %2$@ of the window elapsed": "Used %1$@ of the quota with %2$@ of the window elapsed",
    "Share usage": "Share usage",
    "Share": "Share",
    "Copy image": "Copy image",
    "Copied ✓": "Copied ✓",
    "Save as PNG…": "Save as PNG…",
    "Include": "Include",
    "Range": "Range",
    "Today": "Today",
    "This week": "This week",
    "Last 30 days": "Last 30 days",
    "tokens": "tokens",
    "≈ %@ API-equivalent value": "≈ %@ API-equivalent value",
    "My AI usage": "My AI usage",
    "Daily avg": "Daily avg",
    "Peak day": "Peak day",
    "Top model": "Top model",
    "%@ API-equivalent value": "%@ API-equivalent value",
    "Models": "Models",
    "Active days": "Active days",
    "of %d": "of %d",
    "Show usage": "Show usage",
    "Icon": "Icon",
    "Usage gauge": "Usage gauge",
    "Percentage": "Percentage",
    "Provider split": "Provider split",
    "Today's tokens": "Today's tokens",
    "Today's cost": "Today's cost",
    "Combine any of these — the menu bar shows exactly what you pick.": "Combine any of these — the menu bar shows exactly what you pick.",
}

TRANSLATIONS = {}

TRANSLATIONS["es"] = {
    "30 days": "30 días", "30d": "30d", "60 days": "60 días", "60d": "60d",
    "7 days": "7 días", "7d": "7d", "90 days": "90 días", "90d": "90d",
    "A few Google Fonts, alongside the system font.": "Algunas fuentes de Google Fonts, además de la fuente del sistema.",
    "API-equivalent cost": "Costo equivalente de API",
    "About": "Acerca de", "Alerts": "Alertas", "All providers": "Todos los proveedores",
    "All usage data stays on this Mac. No analytics, telemetry, or TokenOut account.": "Todos los datos de uso permanecen en este Mac. Sin análisis, telemetría ni cuenta de TokenOut.",
    "Appearance": "Apariencia", "Automatic refresh": "Actualización automática",
    "Automatically check for updates": "Buscar actualizaciones automáticamente",
    "TokenOut looks for Claude Code and Codex.": "TokenOut busca Claude Code y Codex.",
    "TokenOut reads each tool's own local data and uses only its existing sign-in.": "TokenOut lee los datos locales de cada herramienta y usa solo su sesión ya iniciada.",
    "TokenOut speeds up automatically above 50% usage and backs off after failures.": "TokenOut acelera automáticamente por encima del 50% de uso y se ralentiza tras fallos.",
    "TokenOut stays in the menu bar and has no Dock icon.": "TokenOut permanece en la barra de menús y no tiene icono en el Dock.",
    "Check for Updates…": "Buscar actualizaciones…", "Connected": "Conectado",
    "Daily usage charts": "Gráficos de uso diario", "Daily usage": "Uso diario", "Daily": "Diario",
    "Default popover": "Vista emergente predeterminada", "Detected": "Detectado", "Display": "Pantalla",
    "Download and install updates automatically": "Descargar e instalar actualizaciones automáticamente",
    "Each alert is sent once per rate-limit reset cycle.": "Cada alerta se envía una vez por ciclo de reinicio del límite.",
    "Every 6 hours": "Cada 6 horas", "Every hour": "Cada hora", "First launch": "Primer inicio",
    "General": "General", "Language": "Idioma", "Launch TokenOut at login": "Abrir TokenOut al iniciar sesión",
    "Limit notifications": "Notificaciones de límite", "Manual update": "Actualización manual",
    "Menu bar": "Barra de menús", "Model and project breakdowns": "Desgloses por modelo y proyecto",
    "No AI coding tools detected": "No se detectaron herramientas de IA",
    "No usage recorded in this range.": "No hay uso registrado en este rango.",
    "Not detected": "No detectado", "Notifications": "Notificaciones",
    "Notify when a limit refills": "Notificar cuando se restablezca un límite", "Now": "Ahora",
    "Popover content": "Contenido de la vista emergente", "Provider detail tiles": "Mosaicos de detalle del proveedor",
    "Providers": "Proveedores", "Quota unavailable": "Cuota no disponible", "Refresh": "Actualizar",
    "Refreshing…": "Actualizando…",
    "Restart TokenOut for a language change to fully apply.": "Reinicia TokenOut para aplicar completamente el cambio de idioma.",
    "Show onboarding again": "Mostrar introducción de nuevo", "Signed out": "Sesión cerrada",
    "Some updates failed": "Algunas actualizaciones fallaron", "Sparkle updates": "Actualizaciones de Sparkle",
    "Stale": "Desactualizado", "Start tracking": "Empezar a rastrear", "Startup": "Inicio",
    "TOKENS": "TOKENS", "Theme": "Tema", "Thresholds": "Umbrales", "Tokens": "Tokens",
    "Tracked tools": "Herramientas monitoreadas", "Updated": "Actualizado",
    "Updates are signed twice: with Developer ID and TokenOut's Sparkle EdDSA key.": "Las actualizaciones se firman dos veces: con Developer ID y la clave EdDSA de Sparkle de TokenOut.",
    "Updates": "Actualizaciones", "Updating…": "Actualizando…",
    "Useful when reviewing local-data access and the Claude Keychain prompt.": "Útil al revisar el acceso a datos locales y el aviso de Keychain de Claude.",
    "Weekly": "Semanal", "What's left — drains to 0%": "Lo que queda — baja hasta 0%",
    "What's used — fills to 100%": "Lo que se usó — sube hasta 100%",
    "Your AI usage, live in the menu bar.": "Tu consumo de tokens de IA, en vivo en la barra de menús.",
    "estimated locally": "estimado localmente", "Fetching fresh data…": "Obteniendo datos nuevos…",
    "Plot charts by dollars or tokens": "Graficar por dólares o tokens", "Quit TokenOut": "Salir de TokenOut",
    "Refresh all providers now (15 s cooldown)": "Actualizar todos los proveedores ahora (espera de 15 s)",
    "Settings": "Ajustes",
    "Theme.system": "Sistema", "Theme.light": "Claro", "Theme.dark": "Oscuro",
    "FontSize.small": "Pequeño", "FontSize.medium": "Mediano", "FontSize.large": "Grande",
    "FontSize.extraLarge": "Extra grande", "Font.system": "Sistema", "Language.system": "Sistema",
    "Overview": "Resumen",
    "Relaunch Now": "Reiniciar ahora",
    "Primary metric": "Métrica principal",
    "Style": "Estilo",
    "Limits show": "Los límites muestran",
    "Default chart range": "Rango de gráfico predeterminado",
    "Chart metric": "Métrica del gráfico",
    "Open on": "Abrir en",
    "Cadence": "Frecuencia",
    "Check frequency": "Frecuencia de comprobación",
    "App language": "Idioma de la aplicación",
    "Size": "Tamaño",
    "Font": "Fuente",
    "Warning": "Aviso",
    "Critical": "Crítico",
    "Website": "Sitio web",
    "Privacy": "Privacidad",
    "Percent only": "Solo porcentaje",
    "Tightest limit": "Límite más ajustado",
    "Fast (30 s)": "Rápida (30 s)",
    "Normal (60 s)": "Normal (60 s)",
    "Relaxed (5 min)": "Relajada (5 min)",
    "refills in %1$@ · at %2$@": "se recarga en %1$@ · a las %2$@",
    "refilled · refreshing…": "recargado · actualizando…",
    "%@ over pace": "%@ por encima del ritmo",
    "%@ in reserve": "%@ de reserva",
    "on pace": "al ritmo",
    "Used %1$@ of the quota with %2$@ of the window elapsed": "Usaste %1$@ de la cuota con %2$@ de la ventana transcurrida",
    "Share usage": "Compartir uso",
    "Share": "Compartir",
    "Copy image": "Copiar imagen",
    "Copied ✓": "Copiado ✓",
    "Save as PNG…": "Guardar como PNG…",
    "Include": "Incluir",
    "Range": "Rango",
    "Today": "Hoy",
    "This week": "Esta semana",
    "Last 30 days": "Últimos 30 días",
    "tokens": "tokens",
    "≈ %@ API-equivalent value": "≈ %@ de valor equivalente en API",
    "My AI usage": "Mi consumo de tokens de IA",
    "Daily avg": "Promedio diario",
    "Peak day": "Día pico",
    "Top model": "Modelo principal",
    "%@ API-equivalent value": "%@ de valor equivalente en API",
    "Models": "Modelos",
    "Active days": "Días activos",
    "of %d": "de %d",
    "Show usage": "Mostrar uso",
    "Icon": "Icono",
    "Usage gauge": "Indicador de uso",
    "Percentage": "Porcentaje",
    "Provider split": "Desglose por proveedor",
    "Today's tokens": "Tokens de hoy",
    "Today's cost": "Costo de hoy",
    "Combine any of these — the menu bar shows exactly what you pick.": "Combina cualquiera de estos: la barra de menús muestra exactamente lo que elijas.",
}

TRANSLATIONS["fr"] = {
    "30 days": "30 jours", "30d": "30 j", "60 days": "60 jours", "60d": "60 j",
    "7 days": "7 jours", "7d": "7 j", "90 days": "90 jours", "90d": "90 j",
    "A few Google Fonts, alongside the system font.": "Quelques polices Google Fonts, en plus de la police système.",
    "API-equivalent cost": "Coût équivalent API",
    "About": "À propos", "Alerts": "Alertes", "All providers": "Tous les fournisseurs",
    "All usage data stays on this Mac. No analytics, telemetry, or TokenOut account.": "Toutes les données d'utilisation restent sur ce Mac. Aucune analyse, télémétrie ou compte TokenOut.",
    "Appearance": "Apparence", "Automatic refresh": "Actualisation automatique",
    "Automatically check for updates": "Rechercher les mises à jour automatiquement",
    "TokenOut looks for Claude Code and Codex.": "TokenOut recherche Claude Code et Codex.",
    "TokenOut reads each tool's own local data and uses only its existing sign-in.": "TokenOut lit les données locales de chaque outil et utilise uniquement sa connexion existante.",
    "TokenOut speeds up automatically above 50% usage and backs off after failures.": "TokenOut accélère automatiquement au-delà de 50 % d'utilisation et ralentit après des échecs.",
    "TokenOut stays in the menu bar and has no Dock icon.": "TokenOut reste dans la barre de menus et n'a pas d'icône dans le Dock.",
    "Check for Updates…": "Rechercher les mises à jour…", "Connected": "Connecté",
    "Daily usage charts": "Graphiques d'utilisation quotidienne", "Daily usage": "Utilisation quotidienne", "Daily": "Quotidien",
    "Default popover": "Fenêtre par défaut", "Detected": "Détecté", "Display": "Affichage",
    "Download and install updates automatically": "Télécharger et installer les mises à jour automatiquement",
    "Each alert is sent once per rate-limit reset cycle.": "Chaque alerte est envoyée une fois par cycle de réinitialisation de limite.",
    "Every 6 hours": "Toutes les 6 heures", "Every hour": "Toutes les heures", "First launch": "Premier lancement",
    "General": "Général", "Language": "Langue", "Launch TokenOut at login": "Lancer TokenOut à la connexion",
    "Limit notifications": "Notifications de limite", "Manual update": "Mise à jour manuelle",
    "Menu bar": "Barre de menus", "Model and project breakdowns": "Détails par modèle et projet",
    "No AI coding tools detected": "Aucun outil de codage IA détecté",
    "No usage recorded in this range.": "Aucune utilisation enregistrée sur cette période.",
    "Not detected": "Non détecté", "Notifications": "Notifications",
    "Notify when a limit refills": "Notifier lors du renouvellement d'une limite", "Now": "Maintenant",
    "Popover content": "Contenu de la fenêtre", "Provider detail tiles": "Vignettes de détail du fournisseur",
    "Providers": "Fournisseurs", "Quota unavailable": "Quota indisponible", "Refresh": "Actualiser",
    "Refreshing…": "Actualisation…",
    "Restart TokenOut for a language change to fully apply.": "Redémarrez TokenOut pour appliquer entièrement le changement de langue.",
    "Show onboarding again": "Revoir la présentation", "Signed out": "Déconnecté",
    "Some updates failed": "Certaines mises à jour ont échoué", "Sparkle updates": "Mises à jour Sparkle",
    "Stale": "Obsolète", "Start tracking": "Commencer le suivi", "Startup": "Démarrage",
    "TOKENS": "JETONS", "Theme": "Thème", "Thresholds": "Seuils", "Tokens": "Jetons",
    "Tracked tools": "Outils suivis", "Updated": "Mis à jour",
    "Updates are signed twice: with Developer ID and TokenOut's Sparkle EdDSA key.": "Les mises à jour sont signées deux fois : avec Developer ID et la clé EdDSA Sparkle de TokenOut.",
    "Updates": "Mises à jour", "Updating…": "Mise à jour…",
    "Useful when reviewing local-data access and the Claude Keychain prompt.": "Utile pour vérifier l'accès aux données locales et l'invite Keychain de Claude.",
    "Weekly": "Hebdomadaire", "What's left — drains to 0%": "Ce qu'il reste — descend à 0 %",
    "What's used — fills to 100%": "Ce qui est utilisé — monte à 100 %",
    "Your AI usage, live in the menu bar.": "Votre consommation de jetons IA, en direct dans la barre de menus.",
    "estimated locally": "estimé localement", "Fetching fresh data…": "Récupération des données…",
    "Plot charts by dollars or tokens": "Tracer les graphiques en dollars ou en jetons", "Quit TokenOut": "Quitter TokenOut",
    "Refresh all providers now (15 s cooldown)": "Actualiser tous les fournisseurs maintenant (délai de 15 s)",
    "Settings": "Réglages",
    "Theme.system": "Système", "Theme.light": "Clair", "Theme.dark": "Sombre",
    "FontSize.small": "Petit", "FontSize.medium": "Moyen", "FontSize.large": "Grand",
    "FontSize.extraLarge": "Très grand", "Font.system": "Système", "Language.system": "Système",
    "Overview": "Aperçu",
    "Relaunch Now": "Relancer maintenant",
    "Primary metric": "Métrique principale",
    "Style": "Style",
    "Limits show": "Les limites affichent",
    "Default chart range": "Période de graphique par défaut",
    "Chart metric": "Métrique du graphique",
    "Open on": "Ouvrir sur",
    "Cadence": "Cadence",
    "Check frequency": "Fréquence de vérification",
    "App language": "Langue de l'application",
    "Size": "Taille",
    "Font": "Police",
    "Warning": "Avertissement",
    "Critical": "Critique",
    "Website": "Site web",
    "Privacy": "Confidentialité",
    "Percent only": "Pourcentage seul",
    "Tightest limit": "Limite la plus proche",
    "Fast (30 s)": "Rapide (30 s)",
    "Normal (60 s)": "Normale (60 s)",
    "Relaxed (5 min)": "Détendue (5 min)",
    "refills in %1$@ · at %2$@": "se recharge dans %1$@ · à %2$@",
    "refilled · refreshing…": "rechargé · actualisation…",
    "%@ over pace": "%@ au-dessus du rythme",
    "%@ in reserve": "%@ en réserve",
    "on pace": "dans le rythme",
    "Used %1$@ of the quota with %2$@ of the window elapsed": "%1$@ du quota utilisé, %2$@ de la fenêtre écoulée",
    "Share usage": "Partager l'utilisation",
    "Share": "Partager",
    "Copy image": "Copier l'image",
    "Copied ✓": "Copié ✓",
    "Save as PNG…": "Enregistrer en PNG…",
    "Include": "Inclure",
    "Range": "Période",
    "Today": "Aujourd'hui",
    "This week": "Cette semaine",
    "Last 30 days": "30 derniers jours",
    "tokens": "jetons",
    "≈ %@ API-equivalent value": "≈ %@ de valeur équivalente API",
    "My AI usage": "Ma consommation de jetons IA",
    "Daily avg": "Moyenne quotidienne",
    "Peak day": "Jour record",
    "Top model": "Modèle principal",
    "%@ API-equivalent value": "%@ de valeur équivalente API",
    "Models": "Modèles",
    "Active days": "Jours actifs",
    "of %d": "sur %d",
    "Show usage": "Afficher l'utilisation",
    "Icon": "Icône",
    "Usage gauge": "Jauge d'utilisation",
    "Percentage": "Pourcentage",
    "Provider split": "Répartition par fournisseur",
    "Today's tokens": "Jetons du jour",
    "Today's cost": "Coût du jour",
    "Combine any of these — the menu bar shows exactly what you pick.": "Combinez librement — la barre de menus affiche exactement votre sélection.",
}

TRANSLATIONS["de"] = {
    "30 days": "30 Tage", "30d": "30 T", "60 days": "60 Tage", "60d": "60 T",
    "7 days": "7 Tage", "7d": "7 T", "90 days": "90 Tage", "90d": "90 T",
    "A few Google Fonts, alongside the system font.": "Einige Google Fonts neben der Systemschrift.",
    "API-equivalent cost": "API-äquivalente Kosten",
    "About": "Info", "Alerts": "Warnungen", "All providers": "Alle Anbieter",
    "All usage data stays on this Mac. No analytics, telemetry, or TokenOut account.": "Alle Nutzungsdaten bleiben auf diesem Mac. Keine Analyse, Telemetrie oder TokenOut-Konto.",
    "Appearance": "Erscheinungsbild", "Automatic refresh": "Automatische Aktualisierung",
    "Automatically check for updates": "Automatisch nach Updates suchen",
    "TokenOut looks for Claude Code and Codex.": "TokenOut sucht nach Claude Code und Codex.",
    "TokenOut reads each tool's own local data and uses only its existing sign-in.": "TokenOut liest die lokalen Daten jedes Tools und nutzt nur dessen bestehende Anmeldung.",
    "TokenOut speeds up automatically above 50% usage and backs off after failures.": "TokenOut beschleunigt automatisch über 50 % Auslastung und drosselt nach Fehlern.",
    "TokenOut stays in the menu bar and has no Dock icon.": "TokenOut bleibt in der Menüleiste und hat kein Dock-Symbol.",
    "Check for Updates…": "Nach Updates suchen…", "Connected": "Verbunden",
    "Daily usage charts": "Tägliche Nutzungsdiagramme", "Daily usage": "Tägliche Nutzung", "Daily": "Täglich",
    "Default popover": "Standardansicht", "Detected": "Erkannt", "Display": "Anzeige",
    "Download and install updates automatically": "Updates automatisch herunterladen und installieren",
    "Each alert is sent once per rate-limit reset cycle.": "Jede Warnung wird einmal pro Rücksetzzyklus des Limits gesendet.",
    "Every 6 hours": "Alle 6 Stunden", "Every hour": "Stündlich", "First launch": "Erster Start",
    "General": "Allgemein", "Language": "Sprache", "Launch TokenOut at login": "TokenOut bei der Anmeldung starten",
    "Limit notifications": "Limit-Benachrichtigungen", "Manual update": "Manuelles Update",
    "Menu bar": "Menüleiste", "Model and project breakdowns": "Aufschlüsselung nach Modell und Projekt",
    "No AI coding tools detected": "Keine KI-Coding-Tools erkannt",
    "No usage recorded in this range.": "Keine Nutzung in diesem Zeitraum erfasst.",
    "Not detected": "Nicht erkannt", "Notifications": "Benachrichtigungen",
    "Notify when a limit refills": "Benachrichtigen, wenn sich ein Limit erneuert", "Now": "Jetzt",
    "Popover content": "Inhalt der Ansicht", "Provider detail tiles": "Anbieter-Detailkacheln",
    "Providers": "Anbieter", "Quota unavailable": "Kontingent nicht verfügbar", "Refresh": "Aktualisieren",
    "Refreshing…": "Wird aktualisiert…",
    "Restart TokenOut for a language change to fully apply.": "Starte TokenOut neu, damit die Sprachänderung vollständig wirksam wird.",
    "Show onboarding again": "Einführung erneut anzeigen", "Signed out": "Abgemeldet",
    "Some updates failed": "Einige Updates sind fehlgeschlagen", "Sparkle updates": "Sparkle-Updates",
    "Stale": "Veraltet", "Start tracking": "Verfolgung starten", "Startup": "Start",
    "TOKENS": "TOKEN", "Theme": "Design", "Thresholds": "Schwellenwerte", "Tokens": "Token",
    "Tracked tools": "Verfolgte Tools", "Updated": "Aktualisiert",
    "Updates are signed twice: with Developer ID and TokenOut's Sparkle EdDSA key.": "Updates werden zweimal signiert: mit Developer ID und TokenOuts Sparkle-EdDSA-Schlüssel.",
    "Updates": "Updates", "Updating…": "Wird aktualisiert…",
    "Useful when reviewing local-data access and the Claude Keychain prompt.": "Nützlich beim Überprüfen des lokalen Datenzugriffs und der Claude-Schlüsselbund-Abfrage.",
    "Weekly": "Wöchentlich", "What's left — drains to 0%": "Was übrig ist — sinkt auf 0 %",
    "What's used — fills to 100%": "Was genutzt wurde — steigt auf 100 %",
    "Your AI usage, live in the menu bar.": "Dein KI-Token-Verbrauch, live in der Menüleiste.",
    "estimated locally": "lokal geschätzt", "Fetching fresh data…": "Neue Daten werden abgerufen…",
    "Plot charts by dollars or tokens": "Diagramme nach Dollar oder Token darstellen", "Quit TokenOut": "TokenOut beenden",
    "Refresh all providers now (15 s cooldown)": "Alle Anbieter jetzt aktualisieren (15 s Abklingzeit)",
    "Settings": "Einstellungen",
    "Theme.system": "System", "Theme.light": "Hell", "Theme.dark": "Dunkel",
    "FontSize.small": "Klein", "FontSize.medium": "Mittel", "FontSize.large": "Groß",
    "FontSize.extraLarge": "Extra groß", "Font.system": "System", "Language.system": "System",
    "Overview": "Übersicht",
    "Relaunch Now": "Jetzt neu starten",
    "Primary metric": "Primäre Metrik",
    "Style": "Stil",
    "Limits show": "Limits zeigen",
    "Default chart range": "Standard-Diagrammbereich",
    "Chart metric": "Diagramm-Metrik",
    "Open on": "Öffnen mit",
    "Cadence": "Taktung",
    "Check frequency": "Prüfintervall",
    "App language": "App-Sprache",
    "Size": "Größe",
    "Font": "Schrift",
    "Warning": "Warnung",
    "Critical": "Kritisch",
    "Website": "Website",
    "Privacy": "Datenschutz",
    "Percent only": "Nur Prozent",
    "Tightest limit": "Knappstes Limit",
    "Fast (30 s)": "Schnell (30 s)",
    "Normal (60 s)": "Normal (60 s)",
    "Relaxed (5 min)": "Entspannt (5 min)",
    "refills in %1$@ · at %2$@": "füllt sich in %1$@ · um %2$@",
    "refilled · refreshing…": "aufgefüllt · aktualisiere…",
    "%@ over pace": "%@ über dem Tempo",
    "%@ in reserve": "%@ in Reserve",
    "on pace": "im Tempo",
    "Used %1$@ of the quota with %2$@ of the window elapsed": "%1$@ des Kontingents verbraucht, %2$@ des Fensters verstrichen",
    "Share usage": "Nutzung teilen",
    "Share": "Teilen",
    "Copy image": "Bild kopieren",
    "Copied ✓": "Kopiert ✓",
    "Save as PNG…": "Als PNG sichern…",
    "Include": "Einbeziehen",
    "Range": "Zeitraum",
    "Today": "Heute",
    "This week": "Diese Woche",
    "Last 30 days": "Letzte 30 Tage",
    "tokens": "Token",
    "≈ %@ API-equivalent value": "≈ %@ API-Gegenwert",
    "My AI usage": "Mein KI-Token-Verbrauch",
    "Daily avg": "Tagesschnitt",
    "Peak day": "Spitzentag",
    "Top model": "Top-Modell",
    "%@ API-equivalent value": "%@ API-Gegenwert",
    "Models": "Modelle",
    "Active days": "Aktive Tage",
    "of %d": "von %d",
    "Show usage": "Nutzung anzeigen",
    "Icon": "Symbol",
    "Usage gauge": "Verbrauchsanzeige",
    "Percentage": "Prozentwert",
    "Provider split": "Anbieter-Aufteilung",
    "Today's tokens": "Tokens heute",
    "Today's cost": "Kosten heute",
    "Combine any of these — the menu bar shows exactly what you pick.": "Beliebig kombinierbar — die Menüleiste zeigt genau deine Auswahl.",
}

TRANSLATIONS["pt"] = {
    "30 days": "30 dias", "30d": "30d", "60 days": "60 dias", "60d": "60d",
    "7 days": "7 dias", "7d": "7d", "90 days": "90 dias", "90d": "90d",
    "A few Google Fonts, alongside the system font.": "Algumas fontes do Google Fonts, além da fonte do sistema.",
    "API-equivalent cost": "Custo equivalente de API",
    "About": "Sobre", "Alerts": "Alertas", "All providers": "Todos os provedores",
    "All usage data stays on this Mac. No analytics, telemetry, or TokenOut account.": "Todos os dados de uso permanecem neste Mac. Sem análises, telemetria ou conta TokenOut.",
    "Appearance": "Aparência", "Automatic refresh": "Atualização automática",
    "Automatically check for updates": "Verificar atualizações automaticamente",
    "TokenOut looks for Claude Code and Codex.": "O TokenOut procura por Claude Code e Codex.",
    "TokenOut reads each tool's own local data and uses only its existing sign-in.": "O TokenOut lê os dados locais de cada ferramenta e usa apenas o login já existente.",
    "TokenOut speeds up automatically above 50% usage and backs off after failures.": "O TokenOut acelera automaticamente acima de 50% de uso e desacelera após falhas.",
    "TokenOut stays in the menu bar and has no Dock icon.": "O TokenOut permanece na barra de menus e não tem ícone no Dock.",
    "Check for Updates…": "Verificar atualizações…", "Connected": "Conectado",
    "Daily usage charts": "Gráficos de uso diário", "Daily usage": "Uso diário", "Daily": "Diário",
    "Default popover": "Janela padrão", "Detected": "Detectado", "Display": "Tela",
    "Download and install updates automatically": "Baixar e instalar atualizações automaticamente",
    "Each alert is sent once per rate-limit reset cycle.": "Cada alerta é enviado uma vez por ciclo de reinício do limite.",
    "Every 6 hours": "A cada 6 horas", "Every hour": "A cada hora", "First launch": "Primeira execução",
    "General": "Geral", "Language": "Idioma", "Launch TokenOut at login": "Abrir o TokenOut ao iniciar sessão",
    "Limit notifications": "Notificações de limite", "Manual update": "Atualização manual",
    "Menu bar": "Barra de menus", "Model and project breakdowns": "Detalhamento por modelo e projeto",
    "No AI coding tools detected": "Nenhuma ferramenta de codificação de IA detectada",
    "No usage recorded in this range.": "Nenhum uso registrado neste período.",
    "Not detected": "Não detectado", "Notifications": "Notificações",
    "Notify when a limit refills": "Notificar quando um limite for renovado", "Now": "Agora",
    "Popover content": "Conteúdo da janela", "Provider detail tiles": "Blocos de detalhes do provedor",
    "Providers": "Provedores", "Quota unavailable": "Cota indisponível", "Refresh": "Atualizar",
    "Refreshing…": "Atualizando…",
    "Restart TokenOut for a language change to fully apply.": "Reinicie o TokenOut para aplicar totalmente a mudança de idioma.",
    "Show onboarding again": "Mostrar introdução novamente", "Signed out": "Sessão encerrada",
    "Some updates failed": "Algumas atualizações falharam", "Sparkle updates": "Atualizações Sparkle",
    "Stale": "Desatualizado", "Start tracking": "Começar a rastrear", "Startup": "Inicialização",
    "TOKENS": "TOKENS", "Theme": "Tema", "Thresholds": "Limites", "Tokens": "Tokens",
    "Tracked tools": "Ferramentas monitoradas", "Updated": "Atualizado",
    "Updates are signed twice: with Developer ID and TokenOut's Sparkle EdDSA key.": "As atualizações são assinadas duas vezes: com o Developer ID e a chave EdDSA do Sparkle do TokenOut.",
    "Updates": "Atualizações", "Updating…": "Atualizando…",
    "Useful when reviewing local-data access and the Claude Keychain prompt.": "Útil ao revisar o acesso a dados locais e o aviso do Keychain do Claude.",
    "Weekly": "Semanal", "What's left — drains to 0%": "O que resta — cai até 0%",
    "What's used — fills to 100%": "O que foi usado — sobe até 100%",
    "Your AI usage, live in the menu bar.": "Seu consumo de tokens de IA, ao vivo na barra de menus.",
    "estimated locally": "estimado localmente", "Fetching fresh data…": "Buscando dados novos…",
    "Plot charts by dollars or tokens": "Plotar gráficos em dólares ou tokens", "Quit TokenOut": "Sair do TokenOut",
    "Refresh all providers now (15 s cooldown)": "Atualizar todos os provedores agora (espera de 15 s)",
    "Settings": "Ajustes",
    "Theme.system": "Sistema", "Theme.light": "Claro", "Theme.dark": "Escuro",
    "FontSize.small": "Pequeno", "FontSize.medium": "Médio", "FontSize.large": "Grande",
    "FontSize.extraLarge": "Extra grande", "Font.system": "Sistema", "Language.system": "Sistema",
    "Overview": "Visão geral",
    "Relaunch Now": "Reiniciar agora",
    "Primary metric": "Métrica principal",
    "Style": "Estilo",
    "Limits show": "Limites mostram",
    "Default chart range": "Intervalo padrão do gráfico",
    "Chart metric": "Métrica do gráfico",
    "Open on": "Abrir em",
    "Cadence": "Frequência",
    "Check frequency": "Frequência de verificação",
    "App language": "Idioma do aplicativo",
    "Size": "Tamanho",
    "Font": "Fonte",
    "Warning": "Aviso",
    "Critical": "Crítico",
    "Website": "Site",
    "Privacy": "Privacidade",
    "Percent only": "Somente porcentagem",
    "Tightest limit": "Limite mais apertado",
    "Fast (30 s)": "Rápida (30 s)",
    "Normal (60 s)": "Normal (60 s)",
    "Relaxed (5 min)": "Relaxada (5 min)",
    "refills in %1$@ · at %2$@": "recarrega em %1$@ · às %2$@",
    "refilled · refreshing…": "recarregado · atualizando…",
    "%@ over pace": "%@ acima do ritmo",
    "%@ in reserve": "%@ de reserva",
    "on pace": "no ritmo",
    "Used %1$@ of the quota with %2$@ of the window elapsed": "Usou %1$@ da cota com %2$@ da janela decorrida",
    "Share usage": "Compartilhar uso",
    "Share": "Compartilhar",
    "Copy image": "Copiar imagem",
    "Copied ✓": "Copiado ✓",
    "Save as PNG…": "Salvar como PNG…",
    "Include": "Incluir",
    "Range": "Período",
    "Today": "Hoje",
    "This week": "Esta semana",
    "Last 30 days": "Últimos 30 dias",
    "tokens": "tokens",
    "≈ %@ API-equivalent value": "≈ %@ em valor equivalente de API",
    "My AI usage": "Meu consumo de tokens de IA",
    "Daily avg": "Média diária",
    "Peak day": "Dia de pico",
    "Top model": "Modelo principal",
    "%@ API-equivalent value": "%@ em valor equivalente de API",
    "Models": "Modelos",
    "Active days": "Dias ativos",
    "of %d": "de %d",
    "Show usage": "Mostrar uso",
    "Icon": "Ícone",
    "Usage gauge": "Medidor de uso",
    "Percentage": "Porcentagem",
    "Provider split": "Divisão por provedor",
    "Today's tokens": "Tokens de hoje",
    "Today's cost": "Custo de hoje",
    "Combine any of these — the menu bar shows exactly what you pick.": "Combine qualquer um deles — a barra de menus mostra exatamente o que você escolher.",
}

TRANSLATIONS["ru"] = {
    "30 days": "30 дней", "30d": "30д", "60 days": "60 дней", "60d": "60д",
    "7 days": "7 дней", "7d": "7д", "90 days": "90 дней", "90d": "90д",
    "A few Google Fonts, alongside the system font.": "Несколько шрифтов Google Fonts, а также системный шрифт.",
    "API-equivalent cost": "Стоимость в эквиваленте API",
    "About": "О программе", "Alerts": "Оповещения", "All providers": "Все провайдеры",
    "All usage data stays on this Mac. No analytics, telemetry, or TokenOut account.": "Все данные об использовании остаются на этом Mac. Никакой аналитики, телеметрии или учётной записи TokenOut.",
    "Appearance": "Внешний вид", "Automatic refresh": "Автообновление",
    "Automatically check for updates": "Автоматически проверять обновления",
    "TokenOut looks for Claude Code and Codex.": "TokenOut ищет Claude Code и Codex.",
    "TokenOut reads each tool's own local data and uses only its existing sign-in.": "TokenOut читает локальные данные каждого инструмента и использует только его существующий вход.",
    "TokenOut speeds up automatically above 50% usage and backs off after failures.": "TokenOut автоматически ускоряется при использовании выше 50% и замедляется после сбоев.",
    "TokenOut stays in the menu bar and has no Dock icon.": "TokenOut остаётся в строке меню и не имеет значка в Dock.",
    "Check for Updates…": "Проверить обновления…", "Connected": "Подключено",
    "Daily usage charts": "Графики ежедневного использования", "Daily usage": "Ежедневное использование", "Daily": "Ежедневно",
    "Default popover": "Окно по умолчанию", "Detected": "Обнаружено", "Display": "Отображение",
    "Download and install updates automatically": "Загружать и устанавливать обновления автоматически",
    "Each alert is sent once per rate-limit reset cycle.": "Каждое оповещение отправляется один раз за цикл сброса лимита.",
    "Every 6 hours": "Каждые 6 часов", "Every hour": "Каждый час", "First launch": "Первый запуск",
    "General": "Основные", "Language": "Язык", "Launch TokenOut at login": "Запускать TokenOut при входе в систему",
    "Limit notifications": "Уведомления о лимитах", "Manual update": "Обновление вручную",
    "Menu bar": "Строка меню", "Model and project breakdowns": "Разбивка по моделям и проектам",
    "No AI coding tools detected": "Инструменты ИИ-кодинга не обнаружены",
    "No usage recorded in this range.": "За этот период данных об использовании нет.",
    "Not detected": "Не обнаружено", "Notifications": "Уведомления",
    "Notify when a limit refills": "Уведомлять об обновлении лимита", "Now": "Сейчас",
    "Popover content": "Содержимое окна", "Provider detail tiles": "Плитки с деталями провайдера",
    "Providers": "Провайдеры", "Quota unavailable": "Квота недоступна", "Refresh": "Обновить",
    "Refreshing…": "Обновление…",
    "Restart TokenOut for a language change to fully apply.": "Перезапустите TokenOut, чтобы смена языка полностью вступила в силу.",
    "Show onboarding again": "Показать введение снова", "Signed out": "Не авторизован",
    "Some updates failed": "Некоторые обновления не удались", "Sparkle updates": "Обновления Sparkle",
    "Stale": "Устарело", "Start tracking": "Начать отслеживание", "Startup": "Запуск",
    "TOKENS": "ТОКЕНЫ", "Theme": "Тема", "Thresholds": "Пороги", "Tokens": "Токены",
    "Tracked tools": "Отслеживаемые инструменты", "Updated": "Обновлено",
    "Updates are signed twice: with Developer ID and TokenOut's Sparkle EdDSA key.": "Обновления подписываются дважды: Developer ID и ключом EdDSA Sparkle от TokenOut.",
    "Updates": "Обновления", "Updating…": "Обновление…",
    "Useful when reviewing local-data access and the Claude Keychain prompt.": "Полезно при проверке доступа к локальным данным и запроса Keychain от Claude.",
    "Weekly": "Еженедельно", "What's left — drains to 0%": "Что осталось — снижается до 0%",
    "What's used — fills to 100%": "Что использовано — растёт до 100%",
    "Your AI usage, live in the menu bar.": "Расход токенов ИИ в реальном времени в строке меню.",
    "estimated locally": "оценено локально", "Fetching fresh data…": "Получение новых данных…",
    "Plot charts by dollars or tokens": "Строить графики в долларах или токенах", "Quit TokenOut": "Выйти из TokenOut",
    "Refresh all providers now (15 s cooldown)": "Обновить всех провайдеров сейчас (задержка 15 с)",
    "Settings": "Настройки",
    "Theme.system": "Системная", "Theme.light": "Светлая", "Theme.dark": "Тёмная",
    "FontSize.small": "Маленький", "FontSize.medium": "Средний", "FontSize.large": "Крупный",
    "FontSize.extraLarge": "Очень крупный", "Font.system": "Системный", "Language.system": "Системный",
    "Overview": "Обзор",
    "Relaunch Now": "Перезапустить сейчас",
    "Primary metric": "Основная метрика",
    "Style": "Стиль",
    "Limits show": "Лимиты показывают",
    "Default chart range": "Диапазон графика по умолчанию",
    "Chart metric": "Метрика графика",
    "Open on": "Открывать на",
    "Cadence": "Периодичность",
    "Check frequency": "Частота проверки",
    "App language": "Язык приложения",
    "Size": "Размер",
    "Font": "Шрифт",
    "Warning": "Предупреждение",
    "Critical": "Критический",
    "Website": "Веб-сайт",
    "Privacy": "Конфиденциальность",
    "Percent only": "Только процент",
    "Tightest limit": "Самый близкий лимит",
    "Fast (30 s)": "Быстро (30 с)",
    "Normal (60 s)": "Обычно (60 с)",
    "Relaxed (5 min)": "Редко (5 мин)",
    "refills in %1$@ · at %2$@": "пополнится через %1$@ · в %2$@",
    "refilled · refreshing…": "обновлено · обновление…",
    "%@ over pace": "%@ выше темпа",
    "%@ in reserve": "%@ в запасе",
    "on pace": "в темпе",
    "Used %1$@ of the quota with %2$@ of the window elapsed": "Использовано %1$@ квоты, прошло %2$@ окна",
    "Share usage": "Поделиться статистикой",
    "Share": "Поделиться",
    "Copy image": "Скопировать изображение",
    "Copied ✓": "Скопировано ✓",
    "Save as PNG…": "Сохранить как PNG…",
    "Include": "Включить",
    "Range": "Период",
    "Today": "Сегодня",
    "This week": "Эта неделя",
    "Last 30 days": "Последние 30 дней",
    "tokens": "токенов",
    "≈ %@ API-equivalent value": "≈ %@ в эквиваленте API",
    "My AI usage": "Мой расход ИИ-токенов",
    "Daily avg": "В среднем в день",
    "Peak day": "Пиковый день",
    "Top model": "Основная модель",
    "%@ API-equivalent value": "%@ в эквиваленте API",
    "Models": "Модели",
    "Active days": "Активные дни",
    "of %d": "из %d",
    "Show usage": "Показать статистику",
    "Icon": "Значок",
    "Usage gauge": "Индикатор использования",
    "Percentage": "Процент",
    "Provider split": "Разбивка по провайдерам",
    "Today's tokens": "Токены за сегодня",
    "Today's cost": "Расходы за сегодня",
    "Combine any of these — the menu bar shows exactly what you pick.": "Комбинируйте как угодно — в строке меню будет ровно то, что вы выбрали.",
}

TRANSLATIONS["ja"] = {
    "30 days": "30日間", "30d": "30日", "60 days": "60日間", "60d": "60日",
    "7 days": "7日間", "7d": "7日", "90 days": "90日間", "90d": "90日",
    "A few Google Fonts, alongside the system font.": "システムフォントに加え、いくつかのGoogle Fontsを利用できます。",
    "API-equivalent cost": "API換算コスト",
    "About": "情報", "Alerts": "アラート", "All providers": "すべてのプロバイダー",
    "All usage data stays on this Mac. No analytics, telemetry, or TokenOut account.": "利用データはすべてこのMac内にとどまります。分析、テレメトリ、TokenOutアカウントは一切ありません。",
    "Appearance": "外観", "Automatic refresh": "自動更新",
    "Automatically check for updates": "自動的にアップデートを確認",
    "TokenOut looks for Claude Code and Codex.": "TokenOutはClaude CodeとCodexを検出します。",
    "TokenOut reads each tool's own local data and uses only its existing sign-in.": "TokenOutは各ツールのローカルデータを読み取り、既存のサインインのみを使用します。",
    "TokenOut speeds up automatically above 50% usage and backs off after failures.": "使用率が50%を超えると自動的に更新頻度を上げ、失敗が続くと頻度を下げます。",
    "TokenOut stays in the menu bar and has no Dock icon.": "TokenOutはメニューバーに常駐し、Dockアイコンはありません。",
    "Check for Updates…": "アップデートを確認…", "Connected": "接続済み",
    "Daily usage charts": "日次使用量グラフ", "Daily usage": "日次使用量", "Daily": "毎日",
    "Default popover": "デフォルトのポップオーバー", "Detected": "検出済み", "Display": "表示",
    "Download and install updates automatically": "アップデートを自動的にダウンロードしてインストール",
    "Each alert is sent once per rate-limit reset cycle.": "各アラートはレート制限のリセットサイクルごとに1回送信されます。",
    "Every 6 hours": "6時間ごと", "Every hour": "1時間ごと", "First launch": "初回起動",
    "General": "一般", "Language": "言語", "Launch TokenOut at login": "ログイン時にTokenOutを起動",
    "Limit notifications": "上限通知", "Manual update": "手動更新",
    "Menu bar": "メニューバー", "Model and project breakdowns": "モデル別・プロジェクト別の内訳",
    "No AI coding tools detected": "AIコーディングツールが検出されません",
    "No usage recorded in this range.": "この期間の使用記録はありません。",
    "Not detected": "未検出", "Notifications": "通知",
    "Notify when a limit refills": "上限がリセットされたら通知", "Now": "今すぐ",
    "Popover content": "ポップオーバーの内容", "Provider detail tiles": "プロバイダー詳細タイル",
    "Providers": "プロバイダー", "Quota unavailable": "クォータを取得できません", "Refresh": "更新",
    "Refreshing…": "更新中…",
    "Restart TokenOut for a language change to fully apply.": "言語変更を完全に反映するにはTokenOutを再起動してください。",
    "Show onboarding again": "オンボーディングを再表示", "Signed out": "サインアウト済み",
    "Some updates failed": "一部の更新に失敗しました", "Sparkle updates": "Sparkleアップデート",
    "Stale": "古いデータ", "Start tracking": "追跡を開始", "Startup": "起動時",
    "TOKENS": "トークン", "Theme": "テーマ", "Thresholds": "しきい値", "Tokens": "トークン",
    "Tracked tools": "追跡対象ツール", "Updated": "更新済み",
    "Updates are signed twice: with Developer ID and TokenOut's Sparkle EdDSA key.": "アップデートはDeveloper IDとTokenOutのSparkle EdDSA鍵の2つで署名されています。",
    "Updates": "アップデート", "Updating…": "更新中…",
    "Useful when reviewing local-data access and the Claude Keychain prompt.": "ローカルデータへのアクセスやClaudeのキーチェーンプロンプトを確認する際に便利です。",
    "Weekly": "週次", "What's left — drains to 0%": "残量表示 — 0%まで減少",
    "What's used — fills to 100%": "使用量表示 — 100%まで増加",
    "Your AI usage, live in the menu bar.": "AIトークンの消費量をメニューバーでリアルタイム表示。",
    "estimated locally": "ローカルで推定", "Fetching fresh data…": "最新データを取得中…",
    "Plot charts by dollars or tokens": "ドルまたはトークンでグラフを表示", "Quit TokenOut": "TokenOutを終了",
    "Refresh all providers now (15 s cooldown)": "今すぐすべてのプロバイダーを更新（15秒のクールダウン）",
    "Settings": "設定",
    "Theme.system": "システム", "Theme.light": "ライト", "Theme.dark": "ダーク",
    "FontSize.small": "小", "FontSize.medium": "中", "FontSize.large": "大",
    "FontSize.extraLarge": "特大", "Font.system": "システム", "Language.system": "システム",
    "Overview": "概要",
    "Relaunch Now": "今すぐ再起動",
    "Primary metric": "主要メトリック",
    "Style": "スタイル",
    "Limits show": "上限の表示",
    "Default chart range": "既定のグラフ範囲",
    "Chart metric": "グラフのメトリック",
    "Open on": "開く対象",
    "Cadence": "頻度",
    "Check frequency": "確認頻度",
    "App language": "アプリの言語",
    "Size": "サイズ",
    "Font": "フォント",
    "Warning": "警告",
    "Critical": "重大",
    "Website": "ウェブサイト",
    "Privacy": "プライバシー",
    "Percent only": "パーセントのみ",
    "Tightest limit": "最も逼迫した上限",
    "Fast (30 s)": "高速（30秒）",
    "Normal (60 s)": "標準（60秒）",
    "Relaxed (5 min)": "低頻度（5分）",
    "refills in %1$@ · at %2$@": "%1$@後に回復 · %2$@",
    "refilled · refreshing…": "回復済み · 更新中…",
    "%@ over pace": "ペースを%@超過",
    "%@ in reserve": "%@の余裕",
    "on pace": "ペース通り",
    "Used %1$@ of the quota with %2$@ of the window elapsed": "ウィンドウ経過 %2$@ の時点でクォータの %1$@ を使用",
    "Share usage": "使用状況を共有",
    "Share": "共有",
    "Copy image": "画像をコピー",
    "Copied ✓": "コピー済み ✓",
    "Save as PNG…": "PNGとして保存…",
    "Include": "含める",
    "Range": "期間",
    "Today": "今日",
    "This week": "今週",
    "Last 30 days": "過去30日間",
    "tokens": "トークン",
    "≈ %@ API-equivalent value": "API換算 ≈ %@",
    "My AI usage": "私のAIトークン消費",
    "Daily avg": "1日平均",
    "Peak day": "ピーク日",
    "Top model": "主要モデル",
    "%@ API-equivalent value": "API換算 %@",
    "Models": "モデル",
    "Active days": "利用日数",
    "of %d": "／%d日",
    "Show usage": "使用状況を表示",
    "Icon": "アイコン",
    "Usage gauge": "使用量ゲージ",
    "Percentage": "パーセント",
    "Provider split": "プロバイダー別",
    "Today's tokens": "今日のトークン",
    "Today's cost": "今日のコスト",
    "Combine any of these — the menu bar shows exactly what you pick.": "自由に組み合わせ可能 — メニューバーには選んだものだけが表示されます。",
}

TRANSLATIONS["zh"] = {
    "30 days": "30 天", "30d": "30天", "60 days": "60 天", "60d": "60天",
    "7 days": "7 天", "7d": "7天", "90 days": "90 天", "90d": "90天",
    "A few Google Fonts, alongside the system font.": "除系统字体外，还提供多款 Google Fonts 字体。",
    "API-equivalent cost": "API 等值费用",
    "About": "关于", "Alerts": "提醒", "All providers": "所有服务商",
    "All usage data stays on this Mac. No analytics, telemetry, or TokenOut account.": "所有使用数据均保留在本机上。没有数据分析、遥测，也不需要 TokenOut 账户。",
    "Appearance": "外观", "Automatic refresh": "自动刷新",
    "Automatically check for updates": "自动检查更新",
    "TokenOut looks for Claude Code and Codex.": "TokenOut 会检测 Claude Code 和 Codex。",
    "TokenOut reads each tool's own local data and uses only its existing sign-in.": "TokenOut 读取每个工具自身的本地数据，仅使用其已有的登录状态。",
    "TokenOut speeds up automatically above 50% usage and backs off after failures.": "使用率超过 50% 时会自动加快刷新，连续失败后会自动放缓。",
    "TokenOut stays in the menu bar and has no Dock icon.": "TokenOut 常驻菜单栏，不显示 Dock 图标。",
    "Check for Updates…": "检查更新…", "Connected": "已连接",
    "Daily usage charts": "每日使用图表", "Daily usage": "每日使用量", "Daily": "每日",
    "Default popover": "默认弹出窗口", "Detected": "已检测到", "Display": "显示",
    "Download and install updates automatically": "自动下载并安装更新",
    "Each alert is sent once per rate-limit reset cycle.": "每个限额重置周期只发送一次提醒。",
    "Every 6 hours": "每 6 小时", "Every hour": "每小时", "First launch": "首次启动",
    "General": "通用", "Language": "语言", "Launch TokenOut at login": "登录时启动 TokenOut",
    "Limit notifications": "限额提醒", "Manual update": "手动更新",
    "Menu bar": "菜单栏", "Model and project breakdowns": "按模型和项目细分",
    "No AI coding tools detected": "未检测到任何 AI 编程工具",
    "No usage recorded in this range.": "此时间范围内没有使用记录。",
    "Not detected": "未检测到", "Notifications": "通知",
    "Notify when a limit refills": "限额重置时通知", "Now": "立即",
    "Popover content": "弹出窗口内容", "Provider detail tiles": "服务商详情卡片",
    "Providers": "服务商", "Quota unavailable": "配额不可用", "Refresh": "刷新",
    "Refreshing…": "正在刷新…",
    "Restart TokenOut for a language change to fully apply.": "重新启动 TokenOut 以完全应用语言更改。",
    "Show onboarding again": "重新显示引导页", "Signed out": "已登出",
    "Some updates failed": "部分更新失败", "Sparkle updates": "Sparkle 更新",
    "Stale": "数据过期", "Start tracking": "开始跟踪", "Startup": "启动",
    "TOKENS": "TOKEN 数", "Theme": "主题", "Thresholds": "阈值", "Tokens": "Token 数",
    "Tracked tools": "已跟踪工具", "Updated": "已更新",
    "Updates are signed twice: with Developer ID and TokenOut's Sparkle EdDSA key.": "更新会经过两次签名：Developer ID 和 TokenOut 的 Sparkle EdDSA 密钥。",
    "Updates": "更新", "Updating…": "正在更新…",
    "Useful when reviewing local-data access and the Claude Keychain prompt.": "在检查本地数据访问权限和 Claude 钥匙串提示时很有用。",
    "Weekly": "每周", "What's left — drains to 0%": "剩余量 — 递减至 0%",
    "What's used — fills to 100%": "已用量 — 递增至 100%",
    "Your AI usage, live in the menu bar.": "在菜单栏实时查看你的 AI Token 消耗。",
    "estimated locally": "本地估算", "Fetching fresh data…": "正在获取最新数据…",
    "Plot charts by dollars or tokens": "按美元或 Token 数绘制图表", "Quit TokenOut": "退出 TokenOut",
    "Refresh all providers now (15 s cooldown)": "立即刷新所有服务商（15 秒冷却时间）",
    "Settings": "设置",
    "Theme.system": "跟随系统", "Theme.light": "浅色", "Theme.dark": "深色",
    "FontSize.small": "小", "FontSize.medium": "中", "FontSize.large": "大",
    "FontSize.extraLarge": "特大", "Font.system": "系统", "Language.system": "跟随系统",
    "Overview": "概览",
    "Relaunch Now": "立即重启",
    "Primary metric": "主要指标",
    "Style": "样式",
    "Limits show": "限额显示",
    "Default chart range": "默认图表范围",
    "Chart metric": "图表指标",
    "Open on": "打开时显示",
    "Cadence": "频率",
    "Check frequency": "检查频率",
    "App language": "应用语言",
    "Size": "大小",
    "Font": "字体",
    "Warning": "警告",
    "Critical": "严重",
    "Website": "网站",
    "Privacy": "隐私",
    "Percent only": "仅百分比",
    "Tightest limit": "最紧张的限额",
    "Fast (30 s)": "快（30 秒）",
    "Normal (60 s)": "正常（60 秒）",
    "Relaxed (5 min)": "宽松（5 分钟）",
    "refills in %1$@ · at %2$@": "%1$@后重置 · %2$@",
    "refilled · refreshing…": "已重置 · 正在刷新…",
    "%@ over pace": "超出进度 %@",
    "%@ in reserve": "剩余余量 %@",
    "on pace": "进度正常",
    "Used %1$@ of the quota with %2$@ of the window elapsed": "时间已过 %2$@，配额已用 %1$@",
    "Share usage": "分享使用情况",
    "Share": "分享",
    "Copy image": "复制图片",
    "Copied ✓": "已复制 ✓",
    "Save as PNG…": "存储为 PNG…",
    "Include": "包含",
    "Range": "范围",
    "Today": "今天",
    "This week": "本周",
    "Last 30 days": "最近 30 天",
    "tokens": "Token",
    "≈ %@ API-equivalent value": "≈ API 等值 %@",
    "My AI usage": "我的 AI Token 消耗",
    "Daily avg": "日均",
    "Peak day": "峰值日",
    "Top model": "主要模型",
    "%@ API-equivalent value": "API 等值 %@",
    "Models": "模型",
    "Active days": "活跃天数",
    "of %d": "/%d 天",
    "Show usage": "显示使用情况",
    "Icon": "图标",
    "Usage gauge": "用量条",
    "Percentage": "百分比",
    "Provider split": "按服务商拆分",
    "Today's tokens": "今日 Token",
    "Today's cost": "今日费用",
    "Combine any of these — the menu bar shows exactly what you pick.": "可任意组合 — 菜单栏只显示你选择的内容。",
}

TRANSLATIONS["hi"] = {
    "30 days": "30 दिन", "30d": "30दि", "60 days": "60 दिन", "60d": "60दि",
    "7 days": "7 दिन", "7d": "7दि", "90 days": "90 दिन", "90d": "90दि",
    "A few Google Fonts, alongside the system font.": "सिस्टम फ़ॉन्ट के साथ-साथ कुछ Google Fonts भी उपलब्ध हैं।",
    "API-equivalent cost": "API-समतुल्य लागत",
    "About": "परिचय", "Alerts": "अलर्ट", "All providers": "सभी प्रदाता",
    "All usage data stays on this Mac. No analytics, telemetry, or TokenOut account.": "सभी उपयोग डेटा इसी Mac पर रहता है। कोई एनालिटिक्स, टेलीमेट्री या TokenOut खाता नहीं है।",
    "Appearance": "रूप-रंग", "Automatic refresh": "स्वचालित रीफ्रेश",
    "Automatically check for updates": "अपडेट के लिए स्वचालित रूप से जाँच करें",
    "TokenOut looks for Claude Code and Codex.": "TokenOut Claude Code और Codex को खोजता है।",
    "TokenOut reads each tool's own local data and uses only its existing sign-in.": "TokenOut हर टूल का अपना लोकल डेटा पढ़ता है और केवल उसकी मौजूदा साइन-इन का उपयोग करता है।",
    "TokenOut speeds up automatically above 50% usage and backs off after failures.": "50% से अधिक उपयोग पर TokenOut अपने आप तेज़ हो जाता है और विफलताओं के बाद धीमा हो जाता है।",
    "TokenOut stays in the menu bar and has no Dock icon.": "TokenOut मेन्यू बार में रहता है और इसका कोई Dock आइकन नहीं है।",
    "Check for Updates…": "अपडेट जाँचें…", "Connected": "कनेक्ट है",
    "Daily usage charts": "दैनिक उपयोग चार्ट", "Daily usage": "दैनिक उपयोग", "Daily": "प्रतिदिन",
    "Default popover": "डिफ़ॉल्ट पॉपओवर", "Detected": "पता चला", "Display": "डिस्प्ले",
    "Download and install updates automatically": "अपडेट स्वचालित रूप से डाउनलोड और इंस्टॉल करें",
    "Each alert is sent once per rate-limit reset cycle.": "प्रत्येक अलर्ट रेट-लिमिट रीसेट चक्र में एक बार भेजा जाता है।",
    "Every 6 hours": "हर 6 घंटे", "Every hour": "हर घंटे", "First launch": "पहली बार लॉन्च",
    "General": "सामान्य", "Language": "भाषा", "Launch TokenOut at login": "लॉगिन पर TokenOut लॉन्च करें",
    "Limit notifications": "लिमिट सूचनाएं", "Manual update": "मैन्युअल अपडेट",
    "Menu bar": "मेन्यू बार", "Model and project breakdowns": "मॉडल और प्रोजेक्ट के अनुसार विवरण",
    "No AI coding tools detected": "कोई AI कोडिंग टूल नहीं मिला",
    "No usage recorded in this range.": "इस सीमा में कोई उपयोग दर्ज नहीं है।",
    "Not detected": "पता नहीं चला", "Notifications": "सूचनाएं",
    "Notify when a limit refills": "लिमिट रीफ़िल होने पर सूचित करें", "Now": "अभी",
    "Popover content": "पॉपओवर सामग्री", "Provider detail tiles": "प्रदाता विवरण टाइलें",
    "Providers": "प्रदाता", "Quota unavailable": "कोटा उपलब्ध नहीं है", "Refresh": "रीफ्रेश करें",
    "Refreshing…": "रीफ्रेश हो रहा है…",
    "Restart TokenOut for a language change to fully apply.": "भाषा परिवर्तन पूरी तरह लागू करने के लिए TokenOut पुनः आरंभ करें।",
    "Show onboarding again": "परिचय फिर से दिखाएं", "Signed out": "साइन आउट है",
    "Some updates failed": "कुछ अपडेट विफल रहे", "Sparkle updates": "Sparkle अपडेट",
    "Stale": "पुराना डेटा", "Start tracking": "ट्रैकिंग शुरू करें", "Startup": "स्टार्टअप",
    "TOKENS": "टोकन", "Theme": "थीम", "Thresholds": "सीमाएं", "Tokens": "टोकन",
    "Tracked tools": "ट्रैक किए गए टूल", "Updated": "अपडेट हुआ",
    "Updates are signed twice: with Developer ID and TokenOut's Sparkle EdDSA key.": "अपडेट दो बार साइन किए जाते हैं: Developer ID और TokenOut की Sparkle EdDSA कुंजी से।",
    "Updates": "अपडेट", "Updating…": "अपडेट हो रहा है…",
    "Useful when reviewing local-data access and the Claude Keychain prompt.": "लोकल-डेटा एक्सेस और Claude Keychain प्रॉम्प्ट की समीक्षा करते समय उपयोगी।",
    "Weekly": "साप्ताहिक", "What's left — drains to 0%": "जो बचा है — 0% तक घटता है",
    "What's used — fills to 100%": "जो उपयोग हुआ — 100% तक बढ़ता है",
    "Your AI usage, live in the menu bar.": "आपका AI टोकन उपयोग, मेन्यू बार में लाइव।",
    "estimated locally": "स्थानीय रूप से अनुमानित", "Fetching fresh data…": "नया डेटा लाया जा रहा है…",
    "Plot charts by dollars or tokens": "डॉलर या टोकन के अनुसार चार्ट बनाएं", "Quit TokenOut": "TokenOut बंद करें",
    "Refresh all providers now (15 s cooldown)": "अभी सभी प्रदाता रीफ्रेश करें (15 सेकंड कूलडाउन)",
    "Settings": "सेटिंग्स",
    "Theme.system": "सिस्टम", "Theme.light": "लाइट", "Theme.dark": "डार्क",
    "FontSize.small": "छोटा", "FontSize.medium": "मध्यम", "FontSize.large": "बड़ा",
    "FontSize.extraLarge": "अतिरिक्त बड़ा", "Font.system": "सिस्टम", "Language.system": "सिस्टम",
    "Overview": "अवलोकन",
    "Relaunch Now": "अभी पुनः आरंभ करें",
    "Primary metric": "मुख्य मीट्रिक",
    "Style": "शैली",
    "Limits show": "सीमाएं दिखाएं",
    "Default chart range": "डिफ़ॉल्ट चार्ट सीमा",
    "Chart metric": "चार्ट मीट्रिक",
    "Open on": "इस पर खोलें",
    "Cadence": "आवृत्ति",
    "Check frequency": "जांच आवृत्ति",
    "App language": "ऐप की भाषा",
    "Size": "आकार",
    "Font": "फ़ॉन्ट",
    "Warning": "चेतावनी",
    "Critical": "गंभीर",
    "Website": "वेबसाइट",
    "Privacy": "गोपनीयता",
    "Percent only": "केवल प्रतिशत",
    "Tightest limit": "सबसे नज़दीकी सीमा",
    "Fast (30 s)": "तेज़ (30 से)",
    "Normal (60 s)": "सामान्य (60 से)",
    "Relaxed (5 min)": "आरामदायक (5 मिनट)",
    "refills in %1$@ · at %2$@": "%1$@ में रीफ़िल · %2$@ पर",
    "refilled · refreshing…": "रीफ़िल हो गया · रीफ़्रेश हो रहा है…",
    "%@ over pace": "गति से %@ आगे",
    "%@ in reserve": "%@ रिज़र्व में",
    "on pace": "गति पर",
    "Used %1$@ of the quota with %2$@ of the window elapsed": "विंडो का %2$@ बीतने पर कोटा का %1$@ उपयोग",
    "Share usage": "उपयोग साझा करें",
    "Share": "साझा करें",
    "Copy image": "छवि कॉपी करें",
    "Copied ✓": "कॉपी हो गया ✓",
    "Save as PNG…": "PNG के रूप में सहेजें…",
    "Include": "शामिल करें",
    "Range": "अवधि",
    "Today": "आज",
    "This week": "इस सप्ताह",
    "Last 30 days": "पिछले 30 दिन",
    "tokens": "टोकन",
    "≈ %@ API-equivalent value": "≈ %@ API-समतुल्य मूल्य",
    "My AI usage": "मेरा AI टोकन उपयोग",
    "Daily avg": "दैनिक औसत",
    "Peak day": "पीक दिन",
    "Top model": "शीर्ष मॉडल",
    "%@ API-equivalent value": "%@ API-समतुल्य मूल्य",
    "Models": "मॉडल",
    "Active days": "सक्रिय दिन",
    "of %d": "%d में से",
    "Show usage": "उपयोग दिखाएं",
    "Icon": "आइकन",
    "Usage gauge": "उपयोग गेज",
    "Percentage": "प्रतिशत",
    "Provider split": "प्रदाता विभाजन",
    "Today's tokens": "आज के टोकन",
    "Today's cost": "आज की लागत",
    "Combine any of these — the menu bar shows exactly what you pick.": "इनमें से कोई भी संयोजन चुनें — मेन्यू बार वही दिखाएगा जो आप चुनेंगे।",
}

TRANSLATIONS["ar"] = {
    "30 days": "30 يومًا", "30d": "30ي", "60 days": "60 يومًا", "60d": "60ي",
    "7 days": "7 أيام", "7d": "7ي", "90 days": "90 يومًا", "90d": "90ي",
    "A few Google Fonts, alongside the system font.": "بضعة خطوط من Google Fonts، إلى جانب خط النظام.",
    "API-equivalent cost": "التكلفة المكافئة لواجهة برمجة التطبيقات",
    "About": "حول", "Alerts": "التنبيهات", "All providers": "جميع الموفرين",
    "All usage data stays on this Mac. No analytics, telemetry, or TokenOut account.": "تبقى جميع بيانات الاستخدام على هذا الـMac. لا تحليلات ولا قياس عن بُعد ولا حساب TokenOut.",
    "Appearance": "المظهر", "Automatic refresh": "التحديث التلقائي",
    "Automatically check for updates": "التحقق التلقائي من التحديثات",
    "TokenOut looks for Claude Code and Codex.": "يبحث TokenOut عن Claude Code وCodex.",
    "TokenOut reads each tool's own local data and uses only its existing sign-in.": "يقرأ TokenOut البيانات المحلية الخاصة بكل أداة ويستخدم فقط تسجيل الدخول الحالي لها.",
    "TokenOut speeds up automatically above 50% usage and backs off after failures.": "يُسرّع TokenOut تلقائيًا عند تجاوز الاستخدام 50% ويبطئ بعد حدوث أخطاء.",
    "TokenOut stays in the menu bar and has no Dock icon.": "يبقى TokenOut في شريط القوائم ولا تظهر له أيقونة في الـDock.",
    "Check for Updates…": "التحقق من التحديثات…", "Connected": "متصل",
    "Daily usage charts": "رسوم الاستخدام اليومي البيانية", "Daily usage": "الاستخدام اليومي", "Daily": "يوميًا",
    "Default popover": "النافذة المنبثقة الافتراضية", "Detected": "تم اكتشافه", "Display": "العرض",
    "Download and install updates automatically": "تنزيل التحديثات وتثبيتها تلقائيًا",
    "Each alert is sent once per rate-limit reset cycle.": "يُرسل كل تنبيه مرة واحدة في كل دورة إعادة تعيين للحد.",
    "Every 6 hours": "كل 6 ساعات", "Every hour": "كل ساعة", "First launch": "أول تشغيل",
    "General": "عام", "Language": "اللغة", "Launch TokenOut at login": "تشغيل TokenOut عند تسجيل الدخول",
    "Limit notifications": "تنبيهات الحد", "Manual update": "تحديث يدوي",
    "Menu bar": "شريط القوائم", "Model and project breakdowns": "تفصيل حسب النموذج والمشروع",
    "No AI coding tools detected": "لم يتم اكتشاف أدوات برمجة بالذكاء الاصطناعي",
    "No usage recorded in this range.": "لا يوجد استخدام مسجّل في هذا النطاق.",
    "Not detected": "لم يُكتشف", "Notifications": "الإشعارات",
    "Notify when a limit refills": "التنبيه عند تجدد الحد", "Now": "الآن",
    "Popover content": "محتوى النافذة المنبثقة", "Provider detail tiles": "بطاقات تفاصيل الموفر",
    "Providers": "الموفرون", "Quota unavailable": "الحصة غير متاحة", "Refresh": "تحديث",
    "Refreshing…": "جارٍ التحديث…",
    "Restart TokenOut for a language change to fully apply.": "أعد تشغيل TokenOut لتطبيق تغيير اللغة بالكامل.",
    "Show onboarding again": "إظهار المقدمة التعريفية مجددًا", "Signed out": "تم تسجيل الخروج",
    "Some updates failed": "فشلت بعض التحديثات", "Sparkle updates": "تحديثات Sparkle",
    "Stale": "بيانات قديمة", "Start tracking": "بدء التتبع", "Startup": "بدء التشغيل",
    "TOKENS": "الرموز", "Theme": "المظهر", "Thresholds": "العتبات", "Tokens": "الرموز",
    "Tracked tools": "الأدوات المتتبَّعة", "Updated": "تم التحديث",
    "Updates are signed twice: with Developer ID and TokenOut's Sparkle EdDSA key.": "يتم توقيع التحديثات مرتين: بمعرّف المطور ومفتاح Sparkle EdDSA الخاص بـ TokenOut.",
    "Updates": "التحديثات", "Updating…": "جارٍ التحديث…",
    "Useful when reviewing local-data access and the Claude Keychain prompt.": "مفيد عند مراجعة الوصول إلى البيانات المحلية وطلب Keychain من Claude.",
    "Weekly": "أسبوعيًا", "What's left — drains to 0%": "المتبقي — ينخفض إلى 0%",
    "What's used — fills to 100%": "المُستخدَم — يرتفع إلى 100%",
    "Your AI usage, live in the menu bar.": "استهلاكك من رموز الذكاء الاصطناعي، مباشرة في شريط القوائم.",
    "estimated locally": "مُقدَّر محليًا", "Fetching fresh data…": "جارٍ جلب بيانات جديدة…",
    "Plot charts by dollars or tokens": "رسم البيانات بالدولار أو بالرموز", "Quit TokenOut": "إنهاء TokenOut",
    "Refresh all providers now (15 s cooldown)": "تحديث جميع الموفرين الآن (فترة انتظار 15 ثانية)",
    "Settings": "الإعدادات",
    "Theme.system": "النظام", "Theme.light": "فاتح", "Theme.dark": "داكن",
    "FontSize.small": "صغير", "FontSize.medium": "متوسط", "FontSize.large": "كبير",
    "FontSize.extraLarge": "كبير جدًا", "Font.system": "النظام", "Language.system": "النظام",
    "Overview": "نظرة عامة",
    "Relaunch Now": "إعادة التشغيل الآن",
    "Primary metric": "المقياس الأساسي",
    "Style": "النمط",
    "Limits show": "عرض الحدود",
    "Default chart range": "نطاق الرسم البياني الافتراضي",
    "Chart metric": "مقياس الرسم البياني",
    "Open on": "الفتح على",
    "Cadence": "الوتيرة",
    "Check frequency": "معدل التحقق",
    "App language": "لغة التطبيق",
    "Size": "الحجم",
    "Font": "الخط",
    "Warning": "تحذير",
    "Critical": "حرج",
    "Website": "الموقع الإلكتروني",
    "Privacy": "الخصوصية",
    "Percent only": "النسبة فقط",
    "Tightest limit": "الحد الأقرب",
    "Fast (30 s)": "سريع (30 ث)",
    "Normal (60 s)": "عادي (60 ث)",
    "Relaxed (5 min)": "متمهل (5 د)",
    "refills in %1$@ · at %2$@": "يتجدد خلال %1$@ · عند %2$@",
    "refilled · refreshing…": "تمت إعادة التعبئة · جارٍ التحديث…",
    "%@ over pace": "فوق الوتيرة بنسبة %@",
    "%@ in reserve": "احتياطي %@",
    "on pace": "على الوتيرة",
    "Used %1$@ of the quota with %2$@ of the window elapsed": "استُخدم %1$@ من الحصة مع مرور %2$@ من النافذة",
    "Share usage": "مشاركة الاستخدام",
    "Share": "مشاركة",
    "Copy image": "نسخ الصورة",
    "Copied ✓": "تم النسخ ✓",
    "Save as PNG…": "حفظ بصيغة PNG…",
    "Include": "تضمين",
    "Range": "النطاق",
    "Today": "اليوم",
    "This week": "هذا الأسبوع",
    "Last 30 days": "آخر 30 يومًا",
    "tokens": "رمز",
    "≈ %@ API-equivalent value": "≈ %@ قيمة مكافئة لواجهة API",
    "My AI usage": "استهلاكي من رموز الذكاء الاصطناعي",
    "Daily avg": "المتوسط اليومي",
    "Peak day": "يوم الذروة",
    "Top model": "النموذج الأبرز",
    "%@ API-equivalent value": "%@ قيمة مكافئة لواجهة API",
    "Models": "النماذج",
    "Active days": "الأيام النشطة",
    "of %d": "من %d",
    "Show usage": "عرض الاستخدام",
    "Icon": "الأيقونة",
    "Usage gauge": "مؤشر الاستخدام",
    "Percentage": "النسبة المئوية",
    "Provider split": "تقسيم الموفرين",
    "Today's tokens": "رموز اليوم",
    "Today's cost": "تكلفة اليوم",
    "Combine any of these — the menu bar shows exactly what you pick.": "اجمع أيًا منها — يعرض شريط القوائم ما تختاره بالضبط.",
}

def escape(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')

missing_report = {}
for lang, table in TRANSLATIONS.items():
    lproj = os.path.join(BASE, f"{lang}.lproj")
    os.makedirs(lproj, exist_ok=True)
    lines = ["/* Generated for TokenOut localization. */"]
    missing = []
    for key, en_val in EN.items():
        val = table.get(key)
        if val is None:
            missing.append(key)
            val = en_val
        lines.append(f'"{escape(key)}" = "{escape(val)}";')
    with open(os.path.join(lproj, "Localizable.strings"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    missing_report[lang] = missing

for lang, missing in missing_report.items():
    print(f"{lang}: {len(TRANSLATIONS[lang])}/{len(EN)} translated, {len(missing)} missing")
    for m in missing:
        print(f"  MISSING: {m}")
